minimum_pre_commit_version: 3.3.0
repos:
    - repo: meta
      hooks:
          - id: check-useless-excludes

    # shell scripts
    - repo: https://github.com/detailyang/pre-commit-shell
      rev: 1.0.5
      hooks:
          - id: shell-lint
            args: [ --format=json ]

    # markdown
    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.35.0
      hooks:
          - id: markdownlint

    # general file formatting
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: check-added-large-files
          - id: check-executables-have-shebangs
          - id: check-merge-conflict
          - id: check-symlinks
          - id: check-xml
          - id: check-yaml
          - id: end-of-file-fixer
          - id: pretty-format-json
          - id: trailing-whitespace
          - id: mixed-line-ending

    # golang
    - repo: https://github.com/dnephin/pre-commit-golang
      rev: v0.5.1
      hooks:
        - id: go-fmt
        - id: go-vet
        - id: go-imports
        - id: golangci-lint

    # security
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.16.1
      hooks:
        - id: gitleaks

    # dockerfiles
    - repo: https://github.com/hadolint/hadolint
      rev: v2.12.0
      hooks:
        - id: hadolint-docker
