apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: [[project-name]]
  description: [[project-description]]
  annotations:
    backstage.io/kubernetes-id: [[project-name]]
    backstage.io/source-location: url:https://github.com/[[repo-owner]]/[[project-name]]
    backstage.io/techdocs-ref: url:https://github.com/[[repo-owner]]/[[project-name]]/tree/main
    giantswarm.io/deployment-names: [[project-name]],[[project-name]]-app
    github.com/project-slug: [[repo-owner]]/[[project-name]]
    circleci.com/project-slug: github/giantswarm/[[project-name]]
spec:
  type: service
  lifecycle: experimental
  owner: [[project-owner]]
