[_]
schema-version = "0.2"

[[io.buildpacks.build.env]]
name = "BP_GO_BUILD_LDFLAGS"
value = "-X main.builtBy=CNBP"

[[io.buildpacks.build.env]]
name = "BP_IMAGE_LABELS"
value = 'org.opencontainers.image.source=https://github.com/giantswarm/devplatform-template-go-service'

[[io.buildpacks.build.env]]
name = "BP_KEEP_FILES"
value = "templates/*:templates/"
