{{- if .Values.pdb.enabled | default false -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "{{.ProjectName}}.fullname" . }}
  labels:
    {{- include "{{.ProjectName}}.labels" . | nindent 4 }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      {{- include "{{.ProjectName}}.selectorLabels" . | nindent 6 }}
{{- end }}
