apiVersion: v1
kind: Service
metadata:
  name: {{ include "devplatform-template-go-service.fullname" . }}
  labels:
    {{- include "devplatform-template-go-service.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "devplatform-template-go-service.selectorLabels" . | nindent 4 }}
