version: 2
project_name: {{.ImageName}}
builds:
  - <<: &build_defaults
      binary: {{.ImageName}}
      main: main.go
      env:
        - CGO_ENABLED=0
    id: linux
    goos:
      - linux
    goarch:
      - amd64
      - arm64
{{`
snapshot:
  version_template: "{{ .Env.CURRENT_TAG }}"
archives:
  - name_template: "{{ .Binary }}_{{ .Env.CURRENT_TAG }}_{{ .Os }}_{{ .Arch }}"
    id: all
    builds: [linux, darwin]
    format: tar.gz
    files:
      - none*
dockers:
  - image_templates:
`}}
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:{{`{{ .Env.CURRENT_TAG }}`}}-amd64"
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:latest-amd64"
{{`
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: amd64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/amd64"
    extra_files:
      - "templates"
  - image_templates:
`}}
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:{{`{{ .Env.CURRENT_TAG }}`}}-arm64"
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:latest-arm64"
{{`
    dockerfile: Dockerfile
    use: buildx
    goos: linux
    goarch: arm64
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{ .Date }}"
      - "--label=org.opencontainers.image.name={{ .ProjectName }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--platform=linux/arm64"
    extra_files:
      - "templates"
docker_manifests:
`}}
  - name_template: "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:{{`{{ .Env.CURRENT_TAG }}`}}"
    image_templates:
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:{{`{{ .Env.CURRENT_TAG }}`}}-amd64"
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:{{`{{ .Env.CURRENT_TAG }}`}}-arm64"
  - name_template: "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:latest"
    image_templates:
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:latest-amd64"
      - "{{.RegistryDomain}}/{{.RegistryName}}/{{.ImageName}}:latest-arm64"
{{`
docker_signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    args:
      - sign
      - "--yes"
      - "${artifact}"
    artifacts: all
    output: true
source:
  enabled: true
`}}
  name_template: "{{ .ProjectName }}_{{`{{ .Env.CURRENT_TAG }}`}}_src"
sboms:
  - artifacts: archive
  - id: source
    artifacts: source
    documents:
      - "{{ .ProjectName }}_{{`{{ .Env.CURRENT_TAG }}`}}_sbom.spdx.json"
{{`
release: {}
checksum: {}
signs:
  - cmd: cosign
    env:
      - COSIGN_EXPERIMENTAL=1
    certificate: "${artifact}.pem"
    args:
      - sign-blob
      - "--output-certificate=${certificate}"
      - "--output-signature=${signature}"
      - "${artifact}"
      - "--yes"
    artifacts: checksum
    output: true
changelog:
  use: github
  groups:
    - title: Features
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "Bug fixes"
      regexp: '^.*?bug(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999
`}}
