name: Block PR until Sub-PR is Merged

on:
  issue_comment:
    types:
      - created
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  block-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check for Sub-PR Status
        id: check_sub_pr
        uses: actions/github-script@v6
        with:
          script: |
            const mainPrNumber = context.payload.pull_request.number;
            const commentPattern = /Pull request #(\d+) was created to preview the result of this PR\.\nMake sure you review and accept the created PR before you merge this one here\./;

            const comments = await github.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: mainPrNumber,
            });

            const subPrComment = comments.data.find(comment => commentPattern.test(comment.body));
            if (!subPrComment) {
              console.log('No sub-PR comment found.');
              return;
            }

            const subPrNumber = subPrComment.body.match(commentPattern)[1];
            const subPr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: subPrNumber,
            });

            if (subPr.data.merged) {
              console.log(`Sub-PR #${subPrNumber} is merged.`);
            } else {
              throw new Error(`Sub-PR #${subPrNumber} is not merged.`);
            }
      - name: Fail if Sub-PR is not merged
        if: ${{ failure() }}
        run: |
          echo "The sub-PR is not merged. Blocking the main PR."
          exit 1
