name: Sub-PR is merged

on:
  issue_comment:
    types:
      - created
  workflow_dispatch: {}

jobs:
  check-sub-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const comments = github.rest.issues.listComments(
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo)
            for (cons c in comments) {
              console.log(c)
            }
