name: Template and release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

defaults:
  run:
    working-directory: rendered-project

jobs:
  validate-and-test:
    uses: "./.github/workflows/validate-test.yaml"
    #defaults:
    #  run:
    #    working-directory: ./rendered-project/
