name: Template and release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

jobs:
  validate-and-test:
    uses: "./rendered-project/.github/workflows/validate-test.yaml@use-boilerplate"
  defaults:
    run:
      working-directory: ./rendered-project/
