name: Template and release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

# defaults:
#   run:
#     working-directory: rendered-project

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: copy actions
        run: cp ./rendered-project/.github/workflows/validate-test.yaml ./.github/workflows
  build:
    # defaults:
    # run:
    # working-directory: ./rendered-project/
    needs: [checkout]
    uses: "./.github/workflows/validate-test.yaml"
