name: Template and release project

on:
  push:
    tags:
      - "*"
  pull_request:
  workflow_dispatch: {}

# defaults:
#   run:
#     working-directory: rendered-project

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Install boilerplate
        run: curl -fsSL https://github.com/gruntwork-io/boilerplate/releases/latest/download/boilerplate_linux_amd64 -o /usr/local/bin/boilerplate && chmod +x /usr/local/bin/boilerplate
      - name: run boilerplate
        run: boilerplate --non-interactive --template-url project-template --output-folder . --var-file boilerplate-values.yml
      - uses: stefanzweifel/git-auto-commit-action@v5
  #  build:
  #    # defaults:
  #    # run:
  #    needs: [checkout]
  #    uses: "./.github/workflows/validate-test.yaml"
