name: Validate and test code

on:
  workflow_call: {}
  workflow_dispatch: {}

env:
  PRE_COMMIT_VERSION: "4.0.1"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: 3.12
      - name: Install golangci
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b "$HOME/.local/bin" v1.54.2
      - name: Install helm-docs
        run: curl -fsSL -o /tmp/hd.deb https://github.com/norwoodj/helm-docs/releases/download/v1.14.2/helm-docs_1.14.2_Linux_x86_64.deb && sudo dpkg -i /tmp/hd.deb && rm /tmp/hd.deb
      - name: Install pipx
        run: sudo apt-get install -y --no-install-recommends pipx
      - name: Install pre-commit
        run: pipx install pre-commit==${{ env.PRE_COMMIT_VERSION }}
      - name: Cache pre-commit hooks
        id: cache-pre-commit-hooks
        uses: actions/cache@v4
        env:
          cache-name: pre-commit-hooks
        with:
          path: ~/.cache/pre-commit
          key: ${{ runner.os }}-pre-commit-${{ env.PRE_COMMIT_VERSION }}-hooks-${{ hashFiles('.pre-commit-config.yaml') }}
      - if: ${{ steps.cache-pre-commit-hooks.outputs.cache-hit != 'true' }}
        name: Install pre-commit hooks
        run: pre-commit install-hooks
      - name: Run pre-commit
        continue-on-error: true
        run: |
          pipx ensurepath
          pre-commit run --show-diff-on-failure --color=always --all-files
  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Set up Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: "1.22.2"
      - name: Write GoList for Nancy
        run: go list -json -m all > go.list
      - name: Run Nancy
        uses: sonatype-nexus-community/nancy-github-action@main
      - name: Test
        run: go test -v ./...
