name: Validate code on each commit
on:
  workflow_dispatch:
  push: []
jobs:
  validate:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pre-commit
        run: pip install -U pre-commit
      - name: Restore pre-commit cache
        uses: actions/cache@v3.3.2
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ hashFiles('.pre-commit-config.yaml') }}
      - name: Run pre-commit
        run: pre-commit run --all-files
